export { default as Main } from "./main/index.js"
export { default as Photo } from "./photo/index.js"
export { default as ErrorPage } from "./error/index.js"
export { default as Portfolio } from "./portfolio/index.js"
export { default as Contact } from "./contact/index.js"