export { default as Main } from "./main/index.js"
export { default as Information } from "./information/index.js"
export { default as ErrorPage } from "./error/index.js"
export { default as Portfolio } from "./portfolio/index.js"
export { default as Contact } from "./contact/index.js"